name: Docker Build and Push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOCKER_IMAGE_NAME: autonomous-agent-system
  DOCKER_HUB_REPO: ${{ secrets.DOCKER_USERNAME }}/socialfi-agent

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            socialfi-agent:latest
            socialfi-agent:${{ github.run_number }}
          cache-from: type=registry,ref=socialfi-agent:buildcache
          cache-to: type=registry,ref=socialfi-agent:buildcache,mode=max 