name: Docker Build and Push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/socialfi-agent:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/socialfi-agent:${{ github.run_number }}
          cache-from: |
            type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/socialfi-agent:buildcache
            type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/socialfi-agent:latest
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/socialfi-agent:buildcache,mode=max
          platforms: linux/amd64
          build-args: |
            BUILDPLATFORM=linux/amd64
            TARGETPLATFORM=linux/amd64 